[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "celvo"
version = "1.1.0"
description = "Private offline speech transcription tool"
requires-python = ">=3.10"
dependencies = [
    "sounddevice",
    "numpy",
    "scipy",
    "requests"
]

[tool.setuptools.packages.find]
where = ["."]
